"""Original flat charcoal and source-evaluation diagrams, with scoped entries."""
from pathlib import Path
import json
b=Path('.scratch/icon-cycles-20260909/cycle-055');out=b/'art'
def save(name,body):(out/(name+'.svg')).write_text('<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><title>'+name.replace('-',' ').title()+'</title>'+body+'</svg>\n')
save('charcoal-drawing','''<rect x="15" y="12" width="91" height="106" rx="5" fill="#C6BBA6"/><rect x="11" y="8" width="91" height="106" rx="5" fill="#F0E6D2"/><path d="M25 81q11-17 23-8t20-10" fill="none" stroke="#A19A8B" stroke-width="15" stroke-linecap="round"/><path d="m25 93 28-11m-23 17 33-13" stroke="#5D5B56" stroke-width="4" stroke-linecap="round"/><path d="m44 66 50-46 13 14-50 46-16 3z" fill="#363F43"/><path d="m44 66 50-46 5 5-50 46-8 12z" fill="#626B6C"/><path d="m94 20 10-9 13 14-10 9z" fill="#414A4D"/><path d="m44 66-3 17 16-3z" fill="#252F34"/><path d="m62 59 5 5m14-23 5 5" stroke="#7D8580" stroke-width="2" stroke-linecap="round"/>''')
save('source-verification','''<rect x="13" y="9" width="72" height="94" rx="6" fill="#B6C6C4"/><rect x="9" y="5" width="72" height="94" rx="6" fill="#EEE6D6"/><path d="M23 23h41M23 36h34M23 49h41" stroke="#879CAE" stroke-width="5" stroke-linecap="round"/><path d="M24 75h14m10 0h13" stroke="#708CA4" stroke-width="4" stroke-linecap="round"/><path d="m32 69 8-7a8 8 0 0 1 11 11l-8 7m-8-2-7 6a8 8 0 0 1-11-11l7-6" fill="none" stroke="#649792" stroke-width="4" stroke-linecap="round"/><circle cx="83" cy="77" r="24" fill="#C6DDD8"/><circle cx="83" cy="77" r="20" fill="#E5EADB"/><path d="m74 76 6 7 13-15" fill="none" stroke="#6D9F86" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><path d="m101 96 14 15" stroke="#637D95" stroke-width="12" stroke-linecap="round"/><circle cx="83" cy="77" r="24" fill="none" stroke="#637D95" stroke-width="6"/>''')
entries=[
('craft-charcoal-drawing','Charcoal drawing','charcoal-drawing','✏️','Drawing and sketching with charcoal explicitly used as the medium.','Graphite-only drawing, digital art, ink painting, charcoal cooking or assuming a portrait subject.'),
('activity-bulb-planting','Bulb planting','bulb-planting','🌷','Planting flower bulbs in gardens or containers, including tulip bulb planting.','General garden maintenance, sowing seeds, viewing mature flowers, or instructions on exact planting depth.'),
('activity-soda-mixing','Soda making','soda-mixing','🥤','Making and mixing nonalcoholic syrup sodas, coffee sodas, soda-fountain drinks and related hands-on soda workshops.','Cocktail mixing, beer brewing, merely drinking soda, sorbet making alone, or a promise of one flavor or ingredient.'),
('activity-source-verification','Source evaluation','source-verification','🔎','Learning to research, evaluate sources and check claims, including verifying online and AI-assisted information.','A guarantee that information is true, security certification, general coding, fraud awareness alone, or unverified claims of misinformation.'),
('equipment-pinhole-camera','Pinhole camera','pinhole-camera','📷','Building or using a lensless pinhole camera, including matchbox-and-film constructions.','Conventional lens cameras, smartphone photography, darkroom printing alone, or a literal construction diagram with working aperture dimensions.')]
(b/'new-entries.json').write_text(json.dumps([dict(id=i,label=l,source='art/'+f+'.svg',provider='custom',fallback_emoji=e,use_for=u,avoid_for=a) for i,l,f,e,u,a in entries],ensure_ascii=False,indent=2)+'\n')
