// One catalog and asset format contract for all frontend pictograms.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { buildPacks } = require('./packs.cjs');
const { gzipSync } = require('node:zlib');
const root = path.resolve(__dirname, '../..');
const hash = bytes => crypto.createHash('sha256').update(bytes).digest('hex').slice(0, 12);
function buildIcons({ check = false } = {}) {
    const custom = JSON.parse(fs.readFileSync(path.join(__dirname, 'catalog.json')));
    const noto = JSON.parse(fs.readFileSync(path.join(__dirname, 'noto.json')));
    if (custom.schema_version !== 1 || noto.schema_version !== 1) throw Error('Unsupported icon catalog');
    const icons = {}, emoji = {};
    const outputs = new Map();
    const artwork = new Map();
    for (const entry of [...custom.icons, ...noto.icons]) {
        if (!/^[a-z0-9][a-z0-9-]*$/.test(entry.id) || Object.hasOwn(icons, entry.id)) throw Error('Invalid/duplicate icon ID');
        if (!/^(art|noto)\/[a-z0-9_-]+\.(svg|png)$/.test(entry.source)) throw Error('Invalid icon path');
        const bytes = fs.readFileSync(path.join(__dirname, entry.source));
        const ext = path.extname(entry.source);
        if (ext === '.svg') {
            const svg = bytes.toString();
            // Upstream art can use inline paint styles, gradients and local hrefs.
            // Neither provider may reference executable or external content.
            if (!/<svg\s/.test(svg) || !/viewBox="0 0 (?:128 128|1000 1000)"/.test(svg) ||
                /<(?:script|foreignObject|image|text|filter|style|animate|set)\b|\bon\w+\s*=|<!ENTITY/i.test(svg) ||
                /(?:href|src)\s*=\s*["'](?!#)|url\(\s*["']?(?!#)/i.test(svg)) {
                throw Error(`Unsafe or unsupported SVG: ${entry.id}`);
            }
        } else if (!bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))) {
            throw Error(`Invalid PNG: ${entry.id}`);
        }
        if (entry.sha256 && crypto.createHash('sha256').update(bytes).digest('hex') !== entry.sha256) throw Error(`Modified upstream art: ${entry.id}`);
        const revision = hash(bytes);
        const url = `images/event-icons/${entry.id}.${revision}${ext}`;
        outputs.set(path.join(root, 'src', url), bytes);
        icons[entry.id] = { id: entry.id, url, revision };
        if (ext === '.svg') artwork.set(entry.id, { revision, svg: bytes.toString('utf8') });
        if (entry.emoji) emoji[entry.emoji] = entry.id;
    }
    const fallbackId = emoji['📅'];
    if (!fallbackId) throw Error('Missing fallback artwork');
    const fallback = noto.icons.find(e => e.id === fallbackId);
    const fallbackUrl = 'data:image/svg+xml;base64,' + fs.readFileSync(path.join(__dirname, fallback.source)).toString('base64');
    const { packs, membership, files } = buildPacks(artwork,
        JSON.parse(fs.readFileSync(path.join(__dirname, 'packs.json'))));
    for (const [url, bytes] of files) outputs.set(path.join(root, 'src', url), bytes);
    for (const icon of Object.values(icons)) {
        if (!membership[icon.id]) continue;
        icon.pack = membership[icon.id];
        icon.gzipBytes = gzipSync(artwork.get(icon.id).svg).length;
    }
    const revision = hash(JSON.stringify({ icons, emoji, packs }));
    outputs.set(path.join(root, 'src/js/core/eventIconCatalog.js'), Buffer.from(
        '// Generated by config/event-icons/build.cjs. All icons use the same renderer.\n' +
        `const IconCatalog = Object.freeze(${JSON.stringify({ revision, icons, emoji, packs, fallbackId, fallbackUrl })});\n`));
    for (const name of ['LICENSE', 'NOTICE', 'REGION-FLAGS-README.txt']) {
        outputs.set(path.join(root, 'src/images/event-icons', `NOTO-${name}.txt`), fs.readFileSync(path.join(__dirname, 'noto', name)));
    }
    for (const [file, bytes] of outputs) {
        if (check) {
            if (!fs.existsSync(file) || !fs.readFileSync(file).equals(bytes)) throw Error(`Stale icon output: ${file}`);
        } else {
            fs.mkdirSync(path.dirname(file), { recursive: true });
            if (!fs.existsSync(file) || !fs.readFileSync(file).equals(bytes)) fs.writeFileSync(file, bytes);
        }
    }
    // Keep old hashes for clients with an older cached bundle.
    return { icons: Object.keys(icons).length, revision,
        packs: Object.keys(packs).length, packedIcons: Object.keys(membership).length,
        startupBytes: files.get(packs.startup.url).length };
}
module.exports = { buildIcons };
if (require.main === module) console.log(buildIcons({ check: process.argv.includes('--check') }));
