#!/usr/bin/env python3
"""Map high-frequency unmapped keywords to curated tags in tag_hierarchy."""

import sys
sys.path.insert(0, 'pipeline')
from db import create_connection

conn = create_connection()
cursor = conn.cursor(dictionary=True)

# Build lookup caches
cursor.execute("SELECT id, name FROM tags WHERE type = 'tag'")
curated_by_name = {r['name']: r['id'] for r in cursor.fetchall()}

cursor.execute("SELECT id, name FROM tags WHERE type = 'keyword'")
keyword_by_name = {r['name']: r['id'] for r in cursor.fetchall()}

cursor.execute("SELECT parent_tag_id, child_tag_id FROM tag_hierarchy")
existing_edges = {(r['parent_tag_id'], r['child_tag_id']) for r in cursor.fetchall()}

def get_curated(name):
    return curated_by_name.get(name)

def get_kw(name):
    return keyword_by_name.get(name)

# =============================================================================
# MAPPINGS: keyword_name -> [curated_parent_name, ...]
# =============================================================================
mappings = [
    # ── MUSIC (general) ──
    ("Performance", ["Music", "Theater"]),
    ("Live Music", ["Music"]),
    ("Showcase", ["Music"]),
    ("Bands", ["Music"]),
    ("Ensemble", ["Music"]),
    ("Concert Series", ["Music"]),
    ("Solo Artist", ["Music"]),
    ("Local Music", ["Music"]),
    ("Local Bands", ["Music"]),
    ("Original Music", ["Music"]),
    ("Music Venue", ["Music"]),
    ("Music Night", ["Music"]),
    ("Music Series", ["Music"]),
    ("Live Gig", ["Music"]),
    ("Live Event", ["Music"]),
    ("Live Show", ["Music"]),
    ("Live Concert", ["Music"]),
    ("Live Entertainment", ["Music", "Nightlife"]),
    ("Band Performance", ["Music"]),
    ("Band Showcase", ["Music"]),
    ("Headliner", ["Music"]),
    ("New Artist", ["Music"]),
    ("New Talent", ["Music"]),
    ("Emerging Artists", ["Music", "Art"]),
    ("Rising Stars", ["Music"]),
    ("Local Artists", ["Art"]),
    ("Local Talent", ["Music"]),
    ("Indie Artist", ["Music"]),
    ("Indie Artists", ["Music"]),
    ("Female Artists", ["Music", "Art"]),
    ("Artists", ["Art"]),
    ("Solo Recital", ["Music"]),
    ("Recital", ["Music"]),
    ("Quintet", ["Music"]),
    ("Trio", ["Music"]),
    ("Duo", ["Music"]),
    ("Multi Instrumentalist", ["Music"]),
    ("Guitarist", ["Guitar"]),
    ("Bassist", ["Music"]),
    ("Drummer", ["Music"]),
    ("Musicianship", ["Music"]),
    ("Musicians", ["Music"]),
    ("Ensemble Performance", ["Music"]),
    ("Composition", ["Music"]),
    ("Music Lovers", ["Music"]),
    ("Music Community", ["Music"]),
    ("Music Scene", ["Music"]),
    ("Music Industry", ["Music"]),
    ("Music Discovery", ["Music"]),
    ("Music Production", ["Music"]),
    ("Music Theory", ["Music", "Education"]),
    ("Eclectic Music", ["Music"]),
    ("Creative Music", ["Music"]),
    ("Improvised Music", ["Music"]),
    ("Improvisational Music", ["Music"]),
    ("Classic Hits", ["Music"]),
    ("American Music", ["Music"]),
    ("Interactive Music", ["Music"]),
    ("Collaborative Music", ["Music"]),
    ("Atmospheric Music", ["Music"]),
    ("Records", ["Music"]),
    ("Record Release", ["Album Release"]),
    ("New Release", ["Music"]),
    ("Vinyl Only", ["Vinyl Culture"]),
    ("Band", ["Music"]),
    ("Harmonies", ["Music"]),
    ("House Band", ["Music"]),
    ("Listening Room", ["Music"]),
    ("Live Events", ["Music"]),
    ("Live Recording", ["Music"]),
    ("Music Concert", ["Music"]),
    ("Concerts", ["Music"]),
    ("Mannes Sounds", ["Music"]),
    ("Student Recital", ["Music", "Education"]),
    ("Student Showcase", ["Music", "Education"]),
    ("Music School", ["Music", "Education"]),
    ("Original Songs", ["Songwriting"]),
    ("Anniversary Tour", ["Music"]),
    ("Live Tour", ["Music"]),
    ("World Tour", ["Music"]),
    ("Breaking Sound", ["Music"]),
    ("Cellar Series", ["Music"]),

    # ── JAZZ ──
    ("Brooklyn Jazz", ["Jazz"]),
    ("Jazz Bass", ["Jazz"]),
    ("Trumpet Jazz", ["Jazz", "Trumpet"]),
    ("Jazz Drums", ["Jazz"]),
    ("Jazz Improvisation", ["Jazz"]),
    ("Jazz Vespers", ["Jazz", "Spirituality"]),
    ("New Orleans Jazz", ["Jazz"]),
    ("Classic Jazz", ["Jazz"]),
    ("Smooth Jazz", ["Jazz"]),
    ("Chamber Jazz", ["Jazz", "Chamber Music"]),
    ("Hot Jazz", ["Jazz"]),
    ("Cuban Jazz", ["Jazz", "Latin Music"]),
    ("Fusion Jazz", ["Jazz Fusion"]),
    ("Vintage Jazz", ["Jazz"]),
    ("Post Bop", ["Jazz"]),
    ("Jazz Band", ["Jazz"]),
    ("Jazz Singer", ["Jazz", "Vocal Jazz"]),
    ("Winter Jazzfest", ["Jazz"]),
    ("Women in Jazz", ["Jazz"]),
    ("Jazz Rock", ["Jazz", "Rock"]),
    ("Organ Trio", ["Jazz"]),
    ("Jazz Community", ["Jazz"]),

    # ── CLASSICAL ──
    ("Beethoven", ["Classical Music"]),
    ("Bach", ["Classical Music"]),
    ("Tchaikovsky", ["Classical Music"]),
    ("Romantic Music", ["Classical Music"]),
    ("Renaissance Music", ["Classical Music", "Early Music"]),
    ("Baroque", ["Baroque Music"]),
    ("Chamber Ensemble", ["Chamber Music"]),
    ("Wind Quintet", ["Classical Music"]),
    ("Youth Orchestra", ["Orchestra", "Family"]),
    ("Symphony Orchestra", ["Symphony"]),
    ("Orchestral Performance", ["Orchestra"]),
    ("Organ Music", ["Music"]),
    ("Cello", ["Music"]),
    ("Clarinet", ["Music"]),
    ("Viola", ["Music"]),
    ("Double Bass", ["Music"]),
    ("Vibraphone", ["Music"]),
    ("Flute", ["Music"]),
    ("Accordion", ["Music"]),
    ("Bellini", ["Classical Music", "Opera"]),

    # ── ROCK ──
    ("Acoustic Rock", ["Rock", "Acoustic"]),
    ("Rock N Roll", ["Rock and Roll"]),
    ("Garage Rock", ["Rock"]),  # already curated? no
    ("Surf Rock", ["Rock"]),
    ("Southern Rock", ["Rock"]),
    ("Country Rock", ["Rock", "Country Music"]),
    ("Funk Rock", ["Rock", "Funk"]),
    ("Noise Rock", ["Rock"]),
    ("Glam Rock", ["Rock"]),
    ("Modern Rock", ["Rock"]),
    ("Guitar Rock", ["Rock"]),
    ("Rock Performance", ["Rock"]),
    ("Emo Night", ["Emo"]),
    ("Emo Music", ["Emo"]),
    ("Power Pop", ["Pop Music", "Rock"]),
    ("Psychedelic", ["Psychedelic Rock"]),

    # ── ELECTRONIC ──
    ("Soulful House", ["House Music"]),
    ("Dark Wave", ["Electronic Music"]),
    ("Electronic Pop", ["Electronic Music", "Pop Music"]),
    ("Indie Electronic", ["Electronic Music"]),
    ("Live Electronic", ["Electronic Music"]),
    ("Electronic Beats", ["Electronic Music"]),
    ("Minimal Techno", ["Techno"]),
    ("Detroit Techno", ["Techno"]),
    ("Disco Party", ["Disco", "Nightlife"]),
    ("Disco Music", ["Disco"]),

    # ── SOUL / R&B ──
    ("Rhythm and Blues", ["R&B"]),
    ("Neo Soul", ["Soul Music", "R&B"]),
    ("Soulful", ["Soul Music"]),

    # ── FOLK / WORLD ──
    ("Irish Folk", ["Irish Music", "Folk Music"]),
    ("Folk Pop", ["Folk Music", "Pop Music"]),
    ("Americana Music", ["Americana"]),
    ("String Band", ["Folk Music"]),
    ("Ragtime", ["Jazz", "Music"]),
    ("Klezmer", ["Jewish Music"]),
    ("Balkan Music", ["World Music"]),
    ("Balkan Brass", ["World Music"]),
    ("Balkan Folk", ["Folk Music", "World Music"]),
    ("Spanish Music", ["World Music"]),
    ("Greek Music", ["World Music"]),
    ("Turkish Music", ["World Music"]),
    ("Caribbean Music", ["World Music"]),
    ("Global Rhythms", ["World Music"]),
    ("Global Sounds", ["World Music"]),
    ("World Fusion", ["World Music"]),
    ("Cultural Music", ["World Music"]),
    ("Cumbia", ["Latin Music"]),
    ("Brazilian Music", ["Latin Music", "World Music"]),
    ("Afrobeat", ["Afrobeats"]),
    ("Afro Caribbean", ["World Music", "Cultural Heritage"]),
    ("Afro Fusion", ["World Music"]),
    ("Old Time Music", ["Folk Music"]),
    ("Yiddish Music", ["Jewish Music"]),
    ("Island Vibes", ["World Music"]),

    # ── POP ──
    ("Art Pop", ["Pop Music"]),
    ("Acoustic Pop", ["Pop Music", "Acoustic"]),
    ("K-Pop", ["Pop Music"]),  # already curated? yes
    ("Alternative Pop", ["Pop Music"]),
    ("Experimental Pop", ["Pop Music"]),

    # ── HIP HOP ──
    ("Trap Music", ["Hip Hop"]),

    # ── SACRED / GOSPEL ──
    ("Gospel", ["Sacred Music"]),
    ("Love Songs", ["Music"]),

    # ── VOCAL ──
    ("Vocal Harmony", ["Vocal Music"]),
    ("Vocal Ensemble", ["Vocal Music"]),
    ("Female Vocalist", ["Vocal Music"]),
    ("Vocal Workshop", ["Vocal Music", "Workshop"]),

    # ── TRIBUTE ──
    ("Tribute Night", ["Tribute Concert"]),

    # ── COMEDY ──
    ("Upstairs Comedy", ["Comedy"]),
    ("Sketch Show", ["Sketch Comedy"]),
    ("Comedy Workshop", ["Comedy", "Workshop"]),
    ("Comedy Special", ["Comedy"]),
    ("Comedy Battle", ["Comedy"]),
    ("Dark Humor", ["Dark Comedy"]),
    ("Live Stand Up", ["Stand-up"]),
    ("Laughs", ["Comedy"]),
    ("Live Laughs", ["Comedy"]),
    ("Ensemble Comedy", ["Comedy"]),
    ("Professional Comedy", ["Comedy"]),
    ("Absurdist Comedy", ["Comedy"]),
    ("Alt Comedy", ["Alternative Comedy"]),
    ("Free Comedy", ["Comedy", "Free"]),
    ("Horror Comedy", ["Comedy"]),
    ("Sci Fi Comedy", ["Comedy"]),
    ("Interactive Comedy", ["Comedy"]),
    ("Adult Humor", ["Comedy"]),
    ("Black Comedy", ["Dark Comedy"]),
    ("Solo Comedy", ["Stand-up"]),
    ("British Comedy", ["Comedy"]),
    ("Dating Comedy", ["Comedy"]),
    ("Midnight Comedy", ["Comedy", "Late Night"]),
    ("Funny", ["Comedy"]),
    ("Laughter", ["Comedy"]),
    ("Spanish Comedy", ["Comedy"]),
    ("Live Comedy", ["Comedy"]),  # check if keyword
    ("Talk Show", ["Comedy"]),
    ("Talent Show", ["Comedy", "Theater"]),
    ("Parody", ["Comedy"]),
    ("Clowning", ["Comedy", "Theater"]),
    ("Humor", ["Comedy"]),  # check if keyword
    ("Classic Comedy", ["Comedy"]),
    ("Interactive Show", ["Comedy", "Theater"]),
    ("Live Improv", ["Improv"]),
    ("Female Comedians", ["Comedy"]),
    ("Women in Comedy", ["Comedy"]),  # check if keyword
    ("Class Showcase", ["Comedy", "Education"]),

    # ── THEATER ──
    ("Broadway", ["Musical Theater", "Theater"]),
    ("Off Broadway", ["Theater"]),
    ("Off Off Broadway", ["Theater"]),
    ("New Work", ["Theater"]),
    ("Play Reading", ["Staged Reading"]),
    ("Theater Life", ["Theater"]),
    ("Theatrical", ["Theater"]),
    ("Classic Theatre", ["Theater"]),
    ("Classic Theater", ["Theater"]),
    ("Contemporary Play", ["Theater"]),
    ("Spanish Theater", ["Theater"]),
    ("Theater Workshop", ["Theater", "Workshop"]),
    ("Stage Production", ["Theater"]),
    ("Stage Show", ["Theater"]),
    ("Works in Progress", ["Theater"]),
    ("Theater Performance", ["Theater"]),
    ("Live Theatre", ["Theater"]),
    ("New Plays", ["Theater"]),
    ("Indie Theatre", ["Theater"]),
    ("Stage", ["Theater"]),
    ("Physical Theatre", ["Performance Art", "Theater"]),
    ("Shakespearean", ["Theater", "Drama"]),
    ("Latinx Theater", ["Theater", "Cultural Heritage"]),
    ("Youth Theater", ["Children", "Theater"]),
    ("Show Tunes", ["Musical Theater"]),
    ("Showtunes", ["Musical Theater"]),
    ("Contemporary Performance", ["Theater"]),
    ("Performance Arts", ["Theater"]),
    ("Short Plays", ["Theater"]),
    ("New Writing", ["Theater", "Literature"]),
    ("Opening Night", ["Theater"]),
    ("Premiere", ["Theater", "Film"]),
    ("Dance Theater", ["Dance", "Theater"]),
    ("Repertory", ["Theater"]),
    ("Family Show", ["Family", "Theater"]),
    ("Family Theater", ["Family", "Theater"]),
    ("Farce", ["Comedy", "Theater"]),

    # ── DANCE ──
    ("Movement", ["Dance"]),
    ("Dance Floor", ["Dance", "Nightlife"]),
    ("Underground Dance", ["Dance"]),
    ("Spanish Dance", ["Dance", "Flamenco"]),
    ("Chinese Dance", ["Dance", "Cultural Heritage"]),
    ("Experimental Dance", ["Dance"]),
    ("Street Dance", ["Dance"]),
    ("Ballroom Dance", ["Social Dance"]),
    ("Inclusive Dance", ["Dance"]),
    ("Community Dance", ["Dance"]),
    ("West African Dance", ["Dance", "Cultural Heritage"]),
    ("Bachata", ["Dance", "Latin Dance"]),
    ("Lion Dance", ["Cultural Heritage", "Dance"]),
    ("Lindy Hop", ["Swing Dance"]),
    ("Dance Event", ["Dance"]),
    ("Music and Movement", ["Dance", "Family"]),
    ("Creative Movement", ["Dance"]),
    ("Movement Art", ["Dance", "Performance Art"]),
    ("Samba", ["Dance", "Latin Music"]),
    ("Mambo", ["Dance", "Latin Music"]),
    ("Tango", ["Argentine Tango"]),

    # ── FILM ──
    ("Cinephile", ["Film"]),
    ("Brunch Movie", ["Film"]),
    ("Oscar Nominated", ["Film"]),
    ("Academy Awards", ["Film"]),
    ("Behind the Scenes", ["Film"]),
    ("Screening", ["Film"]),
    ("Neo Noir", ["Film Noir"]),
    ("Contemporary Cinema", ["Film"]),
    ("Film Discussion", ["Film"]),
    ("Filmmaker QA", ["Film"]),
    ("Contemporary Film", ["Film"]),
    ("Director QA", ["Film"]),
    ("Vintage Film", ["Classic Film"]),
    ("Oscar Shorts", ["Film", "Short Films"]),
    ("Arthouse Film", ["Arthouse"]),
    ("Classic Movies", ["Classic Film"]),
    ("Foreign Film", ["World Cinema"]),
    ("Action Movie", ["Film"]),
    ("Cinema Studies", ["Film History"]),
    ("Kids Movies", ["Family Film"]),
    ("Family Movie", ["Family Film"]),
    ("Hong Kong Cinema", ["World Cinema"]),
    ("Italian Cinema", ["World Cinema"]),
    ("Thai Cinema", ["World Cinema"]),
    ("Moroccan Cinema", ["World Cinema"]),
    ("Music Documentary", ["Documentary", "Music"]),
    ("Midnight Movie", ["Film", "Late Night"]),
    ("Political Film", ["Film"]),
    ("Film Premiere", ["Film"]),
    ("Biographical Drama", ["Film", "Biography"]),
    ("Cinema Q and a", ["Film"]),
    ("Underground Film", ["Film"]),
    ("Modern Cinema", ["Film"]),
    ("Film Club", ["Film"]),
    ("Oscars 2026", ["Film"]),
    ("Oscar Nominee", ["Film"]),
    ("Film Series", ["Film"]),  # check if keyword
    ("Mockumentary", ["Documentary", "Comedy"]),
    ("Sports Drama", ["Film"]),
    ("Political Cinema", ["Film"]),
    ("David Lynch", ["Film"]),
    ("Double Feature", ["Film"]),
    ("Noir", ["Film Noir"]),
    ("Microcinema", ["Film"]),
    ("Retrospective", ["Film"]),
    ("Romantic Drama", ["Film", "Drama"]),
    ("Character Study", ["Film", "Theater"]),
    ("Cinema Lovers", ["Film"]),
    ("Bollywood", ["World Cinema"]),
    ("Body Horror", ["Horror"]),
    ("Supernatural", ["Horror"]),
    ("Melodrama", ["Film", "Theater"]),
    ("Gothic Romance", ["Film", "Literature"]),
    ("Social Commentary", ["Film"]),
    ("Social Realism", ["Film"]),
    ("Social Critique", ["Film"]),
    ("True Story", ["Film", "Documentary"]),
    ("True Stories", ["Film", "Documentary"]),
    ("Rom Com", ["Comedy", "Film"]),
    ("Jewish Film Festival", ["Film"]),
    ("Contemporary Romance", ["Film", "Literature"]),
    ("Espionage", ["Film", "Thriller"]),
    ("Light Show", ["Film", "Art"]),
    ("Movies", ["Film"]),
    ("Science Fiction", ["Sci-fi"]),
    ("Women in Film", ["Film"]),
    ("Art Cinema", ["Arthouse"]),

    # ── ART / VISUAL ARTS ──
    ("Creative Expression", ["Art"]),
    ("Arts and Culture", ["Art"]),
    ("Portraiture", ["Painting"]),
    ("Landscape Painting", ["Painting"]),
    ("Brooklyn Art", ["Art"]),
    ("Art Show", ["Art Exhibition"]),
    ("Decorative Arts", ["Art"]),
    ("Art Studio", ["Art"]),
    ("Renaissance Art", ["Art History"]),
    ("Art Reception", ["Art Gallery"]),
    ("Oil Painting", ["Painting"]),
    ("Art Collection", ["Art"]),
    ("Art Deco", ["Architecture", "Art"]),
    ("Gallery Exhibition", ["Art Exhibition"]),
    ("Gallery Tour", ["Art Gallery", "Guided Tour"]),
    ("Art in the Park", ["Art"]),
    ("Hands on Art", ["Art Workshop"]),
    ("DIY Art", ["DIY", "Art"]),
    ("Feminist Art", ["Art"]),
    ("Accessible Art", ["Art"]),
    ("Media Art", ["Multimedia"]),
    ("Studio Art", ["Art"]),
    ("Black Art", ["Art"]),
    ("New York Art", ["Art"]),
    ("Contemporary Exhibition", ["Art Exhibition"]),
    ("Public Sculpture", ["Sculpture"]),
    ("Art Theory", ["Art", "Education"]),
    ("Art Practice", ["Art"]),
    ("Art Discussion", ["Art"]),
    ("Japanese Art", ["Art"]),
    ("Art School", ["Art", "Education"]),
    ("Korean Art", ["Art"]),
    ("Creative Art", ["Art"]),
    ("Eco Art", ["Art", "Environment"]),
    ("Latin American Art", ["Art", "Cultural Heritage"]),
    ("Graffiti Art", ["Street Art"]),
    ("Travel Art", ["Art"]),
    ("Social Art", ["Art"]),
    ("Archival Art", ["Art"]),
    ("American Art", ["Art"]),
    ("Portrait Art", ["Painting"]),
    ("Collage", ["Collage Art"]),
    ("Modernism", ["Art"]),
    ("Abstract Art", ["Art"]),  # check if keyword
    ("Sound Installation", ["Sound Art"]),
    ("Political Art", ["Art"]),
    ("New Media", ["Art", "Technology"]),
    ("Vintage Signs", ["Art"]),
    ("Art Show", ["Art Exhibition"]),
    ("Gallery", ["Art Gallery"]),
    ("Gallery Reception", ["Art Gallery"]),
    ("Photography Exhibition", ["Photography"]),
    ("Drawing Class", ["Drawing"]),
    ("Still Life", ["Painting"]),
    ("Color Theory", ["Art", "Education"]),
    ("Sketch Night", ["Drawing"]),
    ("Baroque Art", ["Art History"]),
    ("Futurism", ["Art"]),
    ("Sustainable Art", ["Art", "Sustainability"]),
    ("Latinx Art", ["Art", "Cultural Heritage"]),
    ("Tech Art", ["Art", "Technology"]),
    ("Immersive", ["Immersive Experience"]),
    ("Sensory Experience", ["Art"]),
    ("Art Appreciation", ["Art"]),
    ("Group Show", ["Art Exhibition"]),
    ("Group Exhibition", ["Art Exhibition"]),  # check if keyword
    ("Art Conversation", ["Art"]),
    ("Artist in Residence", ["Artist Residency"]),
    ("Artist Showcase", ["Art"]),
    ("Art Museum", ["Museum"]),
    ("Museums", ["Museum"]),
    ("Museum Night", ["Museum"]),
    ("Curator Tour", ["Museum Tour"]),
    ("Math Art", ["Art", "Education"]),
    ("Soundscape", ["Sound Art"]),
    ("Soundscapes", ["Sound Art"]),
    ("Hands on", ["Workshop"]),
    ("Visual Math", ["Art", "Education"]),
    ("Risograph", ["Printmaking"]),
    ("Letterpress", ["Printmaking"]),
    ("Figure Drawing", ["Drawing"]),  # check if keyword
    ("Interdisciplinary", ["Art"]),

    # ── CRAFTS ──
    ("Craftsmanship", ["Crafts"]),
    ("Sewing", ["Fiber Arts"]),
    ("Origami", ["Crafts"]),
    ("Woodworking", ["Crafts"]),
    ("Crochet", ["Fiber Arts"]),
    ("Paper Craft", ["Crafts"]),
    ("Block Printing", ["Printmaking"]),
    ("Zine Making", ["Crafts", "Literature"]),
    ("Glass Art", ["Crafts"]),
    ("Silversmithing", ["Crafts"]),
    ("Adult Coloring", ["Crafts"]),
    ("Needlework", ["Fiber Arts"]),
    ("Calligraphy", ["Crafts"]),
    ("Holiday Crafts", ["Crafts", "Holiday"]),
    ("Ikebana", ["Crafts", "Japanese Culture"]),
    ("Library Crafts", ["Crafts"]),
    ("Clay Art", ["Ceramics"]),
    ("Home Decor", ["Crafts"]),
    ("Craft", ["Crafts"]),
    ("Crochet Love", ["Fiber Arts"]),
    ("Book Art", ["Book Arts"]),
    ("Textile Recycling", ["Fiber Arts", "Sustainability"]),

    # ── LITERATURE ──
    ("Book Lovers", ["Literature"]),
    ("Book Sale", ["Literature"]),
    ("Book Event", ["Literature"]),
    ("Author Reading", ["Author Event"]),
    ("Author Conversation", ["Author Talk"]),
    ("Literary Community", ["Literature"]),
    ("Queer Literature", ["Literature", "LGBTQ"]),
    ("Novel", ["Fiction"]),
    ("Black Authors", ["Literature"]),
    ("Women Writers", ["Literature"]),
    ("Poetry Night", ["Poetry"]),
    ("Literary Talk", ["Literature"]),
    ("Reading Community", ["Literature"]),
    ("Small Press", ["Publishing"]),
    ("Modern Poetry", ["Poetry"]),
    ("Literary Reading", ["Literature"]),
    ("Comics", ["Literature"]),
    ("Selected Shorts", ["Literature", "Short Stories"]),
    ("Visual Poetry", ["Poetry", "Visual Arts"]),
    ("Literary Event", ["Literature"]),  # check if keyword
    ("Literary Arts", ["Literature"]),  # check if keyword
    ("Rare Books", ["Literature"]),
    ("Story SLAM", ["Storytelling"]),
    ("Story", ["Storytelling"]),
    ("Immigrant Stories", ["Literature", "Cultural Heritage"]),

    # ── FOOD / COOKING ──
    ("Italian Cuisine", ["Food"]),
    ("Pasta Making", ["Cooking Class"]),
    ("Fresh Produce", ["Farmers Market"]),
    ("Sweet Treats", ["Food"]),
    ("Culinary Skills", ["Cooking Class"]),
    ("Handmade Pasta", ["Cooking Class"]),
    ("French Pastry", ["Food"]),
    ("Japanese Cuisine", ["Food"]),
    ("Seafood", ["Food"]),
    ("Italian Cooking", ["Cooking Class"]),
    ("Asian Cooking", ["Cooking Class"]),
    ("Thai Cuisine", ["Food"]),
    ("Cheese Making", ["Cooking Workshop"]),
    ("Gourmet Cooking", ["Cooking Class"]),
    ("Cooking Skills", ["Cooking Class"]),
    ("Baking", ["Food"]),
    ("Baking Skills", ["Food"]),
    ("Dumpling Making", ["Cooking Class"]),
    ("Kitchen Skills", ["Cooking Class"]),
    ("Kids Cooking", ["Cooking Class", "Family"]),
    ("Restaurant Week", ["Food"]),
    ("Brooklyn Eats", ["Food"]),
    ("Foodie Event", ["Food"]),
    ("Gourmet Experience", ["Food"]),
    ("Culinary", ["Food"]),
    ("Culinary Arts", ["Food"]),  # check if keyword
    ("Plant Based", ["Food"]),
    ("Prix Fixe", ["Food"]),
    ("Social Dining", ["Food", "Nightlife"]),
    ("Outdoor Dining", ["Food"]),

    # ── WINE / SPIRITS / TASTING ──
    ("Cheese Pairing", ["Tasting"]),
    ("Wine Class", ["Wine Tasting"]),
    ("European Wines", ["Wine Tasting"]),
    ("Sip and Paint", ["Paint and Sip"]),
    ("Champagne Toast", ["Nightlife"]),

    # ── NIGHTLIFE ──
    ("Thursday Night", ["Nightlife"]),
    ("Wednesday Night", ["Nightlife"]),
    ("Tuesday Night", ["Nightlife"]),
    ("Monday Night", ["Nightlife"]),
    ("Bar", ["Nightlife"]),
    ("Night Out", ["Nightlife"]),
    ("Friday Vibes", ["Nightlife"]),
    ("After Work", ["Nightlife"]),
    ("After Work Drinks", ["Happy Hour"]),
    ("Rooftop", ["Nightlife"]),
    ("Rooftop Vibes", ["Nightlife"]),
    ("Rooftop Bar", ["Nightlife"]),
    ("Saturday Vibes", ["Nightlife"]),
    ("Sunday Vibes", ["Nightlife"]),
    ("BYOB", ["Nightlife"]),
    ("Midtown Social", ["Nightlife"]),
    ("Midtown Nightlife", ["Nightlife"]),
    ("Manhattan Nightlife", ["Nightlife"]),
    ("Nightclub", ["Clubbing"]),
    ("Brooklyn Nights", ["Nightlife"]),
    ("Brooklyn Social", ["Nightlife"]),
    ("Brooklyn Bar", ["Nightlife"]),
    ("Brooklyn Bars", ["Nightlife"]),
    ("Neighborhood Bar", ["Nightlife"]),
    ("Dive Bar", ["Nightlife"]),
    ("Irish Pub", ["Nightlife"]),
    ("Lounge", ["Nightlife"]),
    ("Sports Bar", ["Nightlife", "Sports"]),
    ("Meet New People", ["Nightlife"]),
    ("Social Night", ["Nightlife"]),
    ("Social Meetup", ["Nightlife"]),
    ("Socializing", ["Nightlife"]),
    ("Social Event", ["Nightlife"]),  # check if keyword
    ("Black Tie", ["Nightlife"]),
    ("VIP Experience", ["Nightlife"]),
    ("Exclusive Access", ["Nightlife"]),
    ("Weekend Events", ["Nightlife"]),
    ("Weekend Fun", ["Nightlife"]),
    ("Midweek Fun", ["Nightlife"]),
    ("Early Show", ["Nightlife"]),
    ("Afternoon Show", ["Nightlife"]),
    ("Winter Vibes", ["Nightlife"]),
    ("Retro Vibes", ["Nightlife"]),
    ("Vintage Vibes", ["Nightlife"]),
    ("Cozy Vibes", ["Nightlife"]),
    ("Chill Vibes", ["Nightlife"]),
    ("Creative Night", ["Nightlife"]),
    ("Nye Party", ["Nightlife", "Holiday"]),
    ("Valentines Party", ["Nightlife", "Holiday"]),
    ("Birthday Bash", ["Nightlife"]),
    ("Theme Party", ["Party"]),
    ("Themed Party", ["Party"]),  # check if curated
    ("Themed Event", ["Nightlife"]),
    ("DJ Night", ["DJ"]),
    ("Late Night Music", ["Late Night", "Music"]),
    ("Brooklyn Vibes", ["Nightlife"]),
    ("Entertainment", ["Nightlife"]),
    ("Special Event", ["Nightlife"]),
    ("Festive", ["Nightlife"]),
    ("Member Event", ["Nightlife"]),

    # ── SPORTS ──
    ("NBA", ["Basketball"]),
    ("NCAA", ["College Sports"]),
    ("Knicks", ["Basketball"]),
    ("Brooklyn Nets", ["Basketball"]),
    ("NYU Violets", ["College Sports"]),
    ("Super Bowl", ["Football"]),
    ("Rangers", ["Hockey"]),
    ("College Swimming", ["College Sports"]),
    ("NYU Swimming", ["College Sports"]),
    ("College Volleyball", ["College Sports"]),
    ("College Tennis", ["College Sports"]),
    ("NYU Tennis", ["College Sports"]),
    ("NYU Wrestling", ["College Sports"]),
    ("Winter Olympics", ["Sports"]),
    ("Combat Sports", ["Martial Arts"]),
    ("Tennis Skills", ["Sports"]),
    ("Tennis Drills", ["Sports"]),
    ("Junior Tennis", ["Sports"]),
    ("Climbing", ["Sports"]),
    ("Snowshoeing", ["Outdoor", "Winter Sports"]),
    ("Sports Event", ["Sports"]),
    ("NYRR Open Run", ["Running"]),
    ("NYRR", ["Running"]),
    ("Community Run", ["Running"]),  # check if keyword
    ("Shape Up", ["Fitness"]),
    ("Mens Volleyball", ["Sports"]),
    ("NYUMVB", ["Sports"]),
    ("NYUMBB", ["Sports"]),
    ("NYUWBB", ["Sports"]),
    ("NYUTF", ["Sports"]),
    ("Violets Pride", ["Sports"]),

    # ── OUTDOOR / NATURE ──
    ("Adventure", ["Outdoor"]),
    ("Skyline Views", ["Outdoor"]),
    ("Waterfront", ["Outdoor"]),
    ("Its My Park", ["Outdoor", "Community Service"]),
    ("Nature Hike", ["Hiking"]),
    ("Winter Walk", ["Outdoor"]),
    ("Winter Hike", ["Hiking"]),
    ("Outdoor Adventure", ["Outdoor"]),
    ("Outdoor Event", ["Outdoor"]),
    ("Outdoor Activities", ["Outdoor"]),
    ("Outdoor Fun", ["Outdoor"]),
    ("Forest Bathing", ["Nature", "Wellness"]),
    ("Green Thumb", ["Gardening"]),
    ("Garden Tour", ["Gardening"]),
    ("Plant Care", ["Gardening"]),
    ("Green Spaces", ["Parks"]),
    ("Green Space", ["Parks"]),
    ("Public Parks", ["Parks"]),
    ("Biodiversity", ["Nature", "Science"]),
    ("Urban Park Rangers", ["Outdoor"]),
    ("Forest Restoration", ["Conservation"]),
    ("Urban Forestry", ["Conservation"]),
    ("Tree Care", ["Conservation"]),
    ("Soil Health", ["Gardening", "Sustainability"]),
    ("Winter Wildlife", ["Wildlife"]),
    ("Winter Birding", ["Birding"]),
    ("Wildlife Watching", ["Wildlife"]),
    ("Trail Maintenance", ["Conservation", "Outdoor"]),
    ("Parks and Rec", ["Parks"]),
    ("Orchid Care", ["Gardening"]),
    ("Gardening Tips", ["Gardening"]),
    ("Botanical Garden", ["Outdoor"]),
    ("NYBG", ["Outdoor"]),
    ("Urban Exploration", ["Outdoor"]),
    ("Guided Walk", ["Walking Tour"]),
    ("Self Guided Tour", ["Guided Tour"]),
    ("Historical Tour", ["History Tour"]),
    ("Nature Discovery", ["Nature"]),
    ("Nature Science", ["Nature", "Science"]),
    ("Nature Study", ["Nature"]),
    ("Nature Hike", ["Hiking"]),
    ("Winter Activities", ["Outdoor"]),
    ("Biking", ["Cycling"]),
    ("Winter Fun", ["Outdoor"]),
    ("Winter Events", ["Outdoor"]),
    ("Park Cleanup", ["Conservation", "Outdoor"]),  # check if keyword
    ("Master Composter", ["Composting"]),

    # ── EDUCATION ──
    ("Educational", ["Education"]),
    ("Interactive Learning", ["Education"]),
    ("Learning", ["Education"]),
    ("Academic", ["Education"]),
    ("Academic Support", ["Education"]),
    ("Student Life", ["Education"]),
    ("Student Success", ["Education"]),
    ("Skill Building", ["Workshop"]),
    ("ESOL", ["Language Learning"]),
    ("Spanish Language", ["Language Learning"]),
    ("Japanese Language", ["Language Learning"]),
    ("English Learning", ["Language Learning"]),
    ("Language Skills", ["Language Learning"]),
    ("Language Exchange", ["Language Learning"]),
    ("Computer Class", ["Digital Literacy"]),
    ("Computer Basics", ["Digital Literacy"]),  # check if keyword
    ("CLE", ["Education"]),
    ("Graduate School", ["Education"]),
    ("Admissions", ["Education"]),
    ("Youth Education", ["Education"]),
    ("Youth Program", ["Education"]),
    ("Youth Development", ["Education"]),
    ("After School", ["Education"]),
    ("College Prep", ["Education"]),
    ("Spring Semester", ["Education"]),
    ("Winter Break", ["Education"]),
    ("Academic Calendar", ["Education"]),
    ("Public Schools", ["Education"]),
    ("Pedagogy", ["Education"]),
    ("Campus Life", ["Education"]),
    ("Teacher Training", ["Education"]),
    ("Tutoring", ["Education"]),
    ("Educational Talk", ["Lecture"]),
    ("Educational Event", ["Education"]),
    ("Evening Lecture", ["Lecture"]),
    ("Public Talk", ["Lecture"]),
    ("Grand Rounds", ["Lecture"]),
    ("Lunch and Learn", ["Lecture"]),
    ("Online Talk", ["Lecture", "Virtual"]),
    ("Live Talk", ["Lecture"]),
    ("Virtual Talk", ["Lecture", "Virtual"]),
    ("Conference", ["Education"]),
    ("Seminar", ["Education"]),  # check if keyword
    ("Research", ["Education"]),
    ("Medical Education", ["Education"]),
    ("Wisdom", ["Education"]),
    ("Active Learning", ["Education"]),
    ("Problem Solving", ["Education"]),
    ("Library Fun", ["Family"]),
    ("Library Events", ["Education"]),
    ("Library Program", ["Education"]),
    ("Library Event", ["Education"]),
    ("Library Programs", ["Education"]),
    ("Library Resources", ["Education"]),
    ("Library Services", ["Education"]),
    ("Queens Library", ["Education"]),
    ("NYPL", ["Education"]),
    ("Library Tech", ["Education", "Technology"]),
    ("Library Play", ["Family"]),
    ("Library Games", ["Games"]),

    # ── SCIENCE / TECH ──
    ("Astrophysics", ["Astronomy", "Science"]),
    ("Brain Science", ["Neuroscience"]),
    ("Space Exploration", ["Science"]),
    ("Environmental Science", ["Science", "Environment"]),
    ("Marine Life", ["Science", "Nature"]),
    ("Generative AI", ["Artificial Intelligence"]),
    ("AI", ["Artificial Intelligence"]),
    ("Robotics", ["STEM"]),
    ("Virtual Reality", ["Technology"]),
    ("Ed Tech", ["Technology", "Education"]),
    ("Civic Tech", ["Technology", "Civic Engagement"]),
    ("Tech Connect", ["Technology"]),
    ("Tech Help", ["Technology"]),
    ("Tech Education", ["Technology", "Education"]),
    ("Future Tech", ["Technology"]),
    ("Creative Tech", ["Technology", "Art"]),
    ("Data Science", ["Technology"]),  # check if keyword
    ("Audio Engineering", ["Technology", "Music"]),
    ("Audio Design", ["Technology", "Music"]),
    ("Audio Art", ["Sound Art"]),
    ("Digital Culture", ["Technology"]),
    ("Content Creation", ["Technology"]),
    ("Game Design", ["Technology", "Games"]),
    ("Electronics", ["Technology"]),  # check if keyword
    ("Internet Culture", ["Technology"]),
    ("Dinosaurs", ["Science"]),
    ("Kids Science", ["Science", "Family"]),
    ("Anthropology", ["Science"]),
    ("Geology", ["Science"]),
    ("Archaeology", ["Science"]),
    ("STEAM", ["STEM"]),
    ("Anatomy", ["Science"]),
    ("Medicine", ["Science"]),
    ("Civil Engineering", ["Science", "Engineering"]),

    # ── HISTORY ──
    ("Nostalgia", ["History"]),
    ("Revolutionary War", ["American Revolution"]),
    ("Gilded Age", ["History"]),
    ("Founding Fathers", ["American History"]),
    ("Historic House", ["History"]),
    ("African American History", ["Black History"]),
    ("Political History", ["History"]),
    ("Community History", ["History"]),
    ("Medical History", ["History"]),
    ("Living History", ["History"]),
    ("Modern History", ["History"]),
    ("Bronx History", ["History"]),
    ("Immigration History", ["History"]),
    ("World War II", ["Military History"]),
    ("Cultural Memory", ["History", "Cultural Heritage"]),
    ("Remembrance", ["History"]),
    ("Seneca Village", ["History"]),
    ("Queer History", ["History", "LGBTQ"]),  # check if keyword
    ("Historical", ["History"]),
    ("Historical Context", ["History"]),
    ("Food History", ["History", "Food"]),
    ("Thomas Jefferson", ["American History"]),
    ("George Washington", ["American History"]),
    ("Frederick Douglass", ["History", "Black History"]),
    ("Legacy", ["History"]),

    # ── WELLNESS / FITNESS ──
    ("Fitness Class", ["Fitness"]),
    ("Circuit Training", ["Fitness"]),
    ("Fitness Fun", ["Fitness"]),
    ("High Intensity", ["Fitness"]),
    ("Cardio Workout", ["Fitness"]),
    ("Low Impact", ["Fitness"]),
    ("Group Exercise", ["Fitness"]),
    ("Active Living", ["Fitness"]),
    ("Healthy Lifestyle", ["Healthy Living"]),
    ("Healthy Aging", ["Wellness"]),
    ("Tai Chi", ["Wellness", "Martial Arts"]),
    ("Feldenkrais", ["Wellness"]),
    ("Self Love", ["Wellness"]),
    ("Heart Health", ["Health"]),
    ("Stress Reduction", ["Stress Relief"]),
    ("Self Improvement", ["Personal Growth"]),
    ("Wellness Journey", ["Wellness"]),
    ("Gentle Exercise", ["Fitness"]),
    ("Physical Health", ["Fitness"]),
    ("Yin Yoga", ["Yoga"]),
    ("Virtual Yoga", ["Yoga", "Virtual"]),
    ("Body Positivity", ["Wellness"]),
    ("MBSR", ["Mindfulness"]),
    ("HIIT", ["Fitness"]),
    ("Exercise", ["Fitness"]),
    ("Womens Health", ["Wellness"]),
    ("Grief", ["Grief Support"]),
    ("Core Strength", ["Fitness"]),

    # ── FAMILY ──
    ("Kids Week", ["Family"]),
    ("Toddler Play", ["Family"]),
    ("Toddler Life", ["Family"]),
    ("Baby Storytime", ["Storytime"]),
    ("Kids Reading", ["Literature", "Family"]),
    ("Teen Art", ["Art", "Family"]),
    ("Teen Events", ["Family"]),
    ("Teens", ["Family"]),
    ("Teen Time", ["Family"]),
    ("Little Movers", ["Family"]),
    ("Infant Development", ["Family"]),
    ("Youth Performance", ["Family", "Theater"]),
    ("Childrens Museum", ["Museum", "Family"]),
    ("Childrens Music", ["Kids Music"]),
    ("Childrens Event", ["Family Event"]),
    ("Childrens Events", ["Family Event"]),
    ("Family Bonding", ["Family"]),
    ("Families", ["Family"]),
    ("Open Play", ["Family"]),
    ("Play Based Learning", ["Family", "Education"]),
    ("Learning Through Play", ["Family", "Education"]),
    ("Active Play", ["Family"]),
    ("Sensory Play", ["Family"]),  # check if keyword
    ("Disney", ["Family", "Film"]),
    ("Early Childhood", ["Family"]),  # check if keyword
    ("Beginner Friendly", ["Family"]),
    ("Student Exhibition", ["Education"]),
    ("Youth Art", ["Art", "Family"]),
    ("Child Development", ["Family"]),
    ("Childrens Books", ["Literature", "Family"]),  # check if keyword
    ("Winter Wonderland", ["Family"]),
    ("Summer Camp", ["Family"]),
    ("Picture Books", ["Family", "Literature"]),  # check if keyword

    # ── SPIRITUALITY ──
    ("Lent", ["Spirituality"]),
    ("Episcopal", ["Spirituality"]),
    ("Ash Wednesday", ["Spirituality"]),
    ("Quaker", ["Spirituality"]),
    ("Ritual", ["Spirituality"]),
    ("Tarot", ["Spirituality"]),
    ("Spiritual Practice", ["Spirituality"]),
    ("Spiritual Journey", ["Spirituality"]),
    ("Religious Service", ["Worship"]),
    ("Religious Studies", ["Spirituality", "Education"]),
    ("Interfaith", ["Spirituality"]),
    ("Sunday Platform", ["Spirituality"]),
    ("Fellowship", ["Spirituality"]),
    ("Humanism", ["Philosophy"]),
    ("Astrology", ["Spirituality"]),

    # ── GAMES ──
    ("Logic Puzzles", ["Games"]),
    ("Puzzles", ["Puzzle"]),
    ("RPG", ["Tabletop RPG"]),
    ("Fantasy RPG", ["Tabletop RPG"]),
    ("Roleplaying Game", ["Tabletop RPG"]),
    ("Tabletop RPG", ["Tabletop"]),  # check if keyword
    ("Social Deduction", ["Games"]),
    ("Escape Room", ["Games"]),
    ("Bar Trivia", ["Trivia"]),
    ("Brooklyn Trivia", ["Trivia"]),
    ("Bingo Night", ["Bingo"]),

    # ── HOLIDAY ──
    ("Valentines Day", ["Holiday"]),
    ("New Years Eve", ["Holiday"]),
    ("MLK Day", ["Holiday", "Cultural Heritage"]),
    ("Presidents Day", ["Holiday"]),
    ("Earth Month", ["Sustainability"]),
    ("Mardi Gras", ["Cultural Heritage", "Holiday"]),
    ("Purim", ["Cultural Heritage", "Spirituality"]),
    ("Chinese New Year", ["Lunar New Year"]),
    ("Holiday Market", ["Holiday"]),
    ("Holiday Tradition", ["Holiday"]),
    ("Valentine Day", ["Holiday"]),
    ("Valentine Events", ["Holiday"]),
    ("Valentines Event", ["Holiday"]),
    ("Valentine Event", ["Holiday"]),
    ("Valentine", ["Holiday"]),
    ("Galentines Day", ["Holiday"]),
    ("New Years Day", ["Holiday"]),
    ("New Year", ["Holiday"]),
    ("NYE 2026", ["Holiday"]),
    ("Year of the Horse", ["Cultural Heritage"]),
    ("Spring Equinox", ["Holiday"]),
    ("Memorial", ["Holiday"]),

    # ── CULTURAL HERITAGE ──
    ("Jewish Heritage", ["Jewish Culture"]),
    ("Jewish Life", ["Jewish Culture"]),
    ("Jewish Identity", ["Jewish Culture"]),
    ("Black Excellence", ["Cultural Heritage"]),
    ("Cultural Studies", ["Cultural Heritage", "Education"]),
    ("Cultural Education", ["Cultural Heritage", "Education"]),
    ("Cultural Fusion", ["Cultural Heritage"]),
    ("African Diaspora", ["Cultural Heritage"]),
    ("Asian American", ["Cultural Heritage"]),
    ("BIPOC", ["Cultural Heritage"]),
    ("Intergenerational", ["Cultural Heritage"]),
    ("Global Culture", ["Cultural Heritage"]),
    ("Cultural Arts", ["Cultural Heritage", "Art"]),
    ("Cultural Diversity", ["Cultural Heritage"]),
    ("Deaf Culture", ["Cultural Heritage"]),
    ("Afrofuturism", ["Cultural Heritage", "Art"]),
    ("Tradition", ["Cultural Heritage"]),
    ("Harlem Renaissance", ["Cultural Heritage", "History"]),  # check if keyword

    # ── COMMUNITY / GOVERNMENT ──
    ("Community Board", ["Government"]),
    ("Brooklyn CB9", ["Government"]),
    ("Manhattan CB8", ["Government"]),
    ("Manhattan CB1", ["Government"]),
    ("Manhattan CB12", ["Government"]),
    ("Manhattan CB4", ["Government"]),
    ("Brooklyn CB4", ["Government"]),
    ("Brooklyn CB14", ["Government"]),
    ("Manhattan CB3", ["Government"]),
    ("Brooklyn CB1", ["Government"]),
    ("Manhattan CB2", ["Government"]),
    ("Manhattan CB9", ["Government"]),
    ("Brooklyn CB6", ["Government"]),
    ("Bronx CB9", ["Government"]),
    ("Manhattan CB6", ["Government"]),
    ("Manhattan CB10", ["Government"]),
    ("Bronx CB2", ["Government"]),
    ("Queens CB1", ["Government"]),
    ("Queens CB5", ["Government"]),
    ("Manhattan CB5", ["Government"]),
    ("Brooklyn CB8", ["Government"]),
    ("Brooklyn CB2", ["Government"]),
    ("Queens CB2", ["Government"]),
    ("Zone One", ["Government"]),
    ("Community Planning", ["Government"]),
    ("Public Forum", ["Government"]),
    ("Community Governance", ["Government"]),  # check if keyword
    ("Strategic Planning", ["Government"]),
    ("Liquor License", ["Government"]),
    ("Safe Streets", ["Urban Planning"]),
    ("City Planning", ["Urban Planning"]),
    ("Transit", ["Urban Planning"]),
    ("Public Works", ["Government"]),
    ("DSA", ["Politics"]),
    ("Voting Rights", ["Activism", "Politics"]),
    ("Civic Duty", ["Civic Engagement"]),
    ("Civic Action", ["Civic Engagement"]),
    ("Social Movements", ["Activism"]),
    ("Social Action", ["Activism"]),
    ("Social Justice", ["Activism"]),  # check if keyword
    ("Tax the Rich", ["Politics"]),
    ("Resistance", ["Activism"]),
    ("Social Issues", ["Community"]),
    ("Diversity", ["Community"]),
    ("Inclusion", ["Community"]),
    ("Representation", ["Community"]),
    ("Human Services", ["Community Support"]),
    ("Hunger Relief", ["Community Support"]),
    ("Food Pantry", ["Community Support"]),
    ("Food Rescue", ["Community Support"]),
    ("Food Security", ["Community Support"]),
    ("Food Justice", ["Community Support"]),
    ("Tax Prep", ["Tax Help"]),
    ("Free Tax Prep", ["Tax Help"]),
    ("Tax Season", ["Tax Help"]),
    ("Resume Help", ["Community Support"]),
    ("Public Benefits", ["Community Support"]),
    ("Immigration", ["Community Support"]),  # check if keyword
    ("Immigrant Services", ["Community Support"]),
    ("Social Services", ["Community Support"]),  # check if keyword
    ("Giving Back", ["Volunteer"]),
    ("Community Outreach", ["Community"]),
    ("Community Development", ["Community"]),
    ("Community Resources", ["Community"]),
    ("Community Discussion", ["Community"]),
    ("Community Concert", ["Community", "Music"]),
    ("Community Education", ["Community", "Education"]),
    ("Community Market", ["Community"]),
    ("Community Partner", ["Community"]),
    ("Community Learning", ["Community", "Education"]),
    ("Community Fun", ["Community"]),
    ("Community Social", ["Community"]),
    ("Community Safety", ["Community"]),
    ("Community Space", ["Community"]),
    ("Community Impact", ["Community"]),
    ("Philanthropy", ["Fundraiser"]),  # check if keyword
    ("Benefit Event", ["Fundraiser"]),
    ("Nonprofit", ["Community"]),
    ("Non Profit", ["Community"]),
    ("Anniversary Celebration", ["Community"]),
    ("Awards Ceremony", ["Community"]),
    ("Accessible Art", ["Art"]),
    ("Accessibility", ["Community"]),
    ("Neurodiversity", ["Community"]),
    ("Sensory Friendly", ["Community"]),  # check if keyword
    ("LGBTQ", ["Community"]),  # check if keyword
    ("Queer Party", ["Queer Nightlife"]),
    ("Queer Community", ["LGBTQ"]),
    ("Queer Space", ["LGBTQ"]),
    ("Queer Joy", ["LGBTQ"]),
    ("Queer Power", ["LGBTQ"]),
    ("Open Call", ["Art"]),
    ("Open Captions", ["Community"]),

    # ── PROFESSIONAL DEVELOPMENT ──
    ("Grant Writing", ["Professional Development"]),
    ("Career Fair", ["Professional Development"]),
    ("Employment", ["Professional Development"]),
    ("Mentoring", ["Mentorship"]),
    ("Communication Skills", ["Professional Development"]),
    ("Communication", ["Professional Development"]),
    ("Coaching", ["Professional Development"]),
    ("Business", ["Professional Development"]),
    ("Productivity", ["Professional Development"]),
    ("Leadership", ["Professional Development"]),  # check if keyword

    # ── PODCAST ──
    ("Podcast Live", ["Live Podcast"]),

    # ── NEIGHBORHOOD-SPECIFIC (skip most, but some map to nightlife/community) ──
    ("Chelsea Events", ["Community"]),
    ("Bushwick Events", ["Community"]),
    ("Harlem Events", ["Community"]),
    ("Astoria Events", ["Community"]),
    ("Midtown Events", ["Community"]),
    ("Brooklyn Gigs", ["Music"]),

    # ── MISC ──
    ("Residency", ["Artist Residency"]),
    ("Collaboration", ["Art"]),
    ("Matinee", ["Theater"]),
    ("Masterclass", ["Master Class"]),
    ("Masterpiece", ["Art"]),
    ("Q&A", ["Education"]),
    ("Interactive", ["Education"]),
    ("Beginner Dance", ["Dance"]),  # check if keyword
    ("We Speak", ["Language Learning"]),
    ("Bilingual", ["Language Learning"]),
    ("Vintage", ["Art"]),
    ("Vintage Style", ["Art"]),
    ("Retro", ["Art"]),
    ("Safety Training", ["Education"]),
    ("Observation Deck", ["Outdoor"]),
    ("Views", ["Outdoor"]),
    ("Skyline", ["Outdoor"]),
    ("Afternoon Tea", ["Food"]),
    ("Potluck", ["Community"]),
    ("Spring Festival", ["Community", "Holiday"]),
    ("Brunch", ["Food"]),  # check if keyword
    ("Romantic Dinner", ["Food", "Date Night"]),
    ("Romantic Evening", ["Nightlife", "Date Night"]),
    ("Dating", ["Nightlife"]),
    ("Singles Event", ["Nightlife"]),  # check if keyword
    ("Makers", ["Makerspace"]),
    ("Dog Friendly", ["Community"]),
    ("Dog Lovers", ["Community"]),
    ("Animal Rescue", ["Community", "Volunteer"]),
    ("Charity Sale", ["Fundraiser"]),
    ("Journaling", ["Wellness"]),
    ("Letter Writing", ["Literature"]),
    ("Mediation", ["Community Support"]),
    ("Organizing", ["Activism"]),
    ("Self Care", ["Wellness"]),  # check if keyword
    ("Retreat", ["Wellness"]),
    ("Recovery", ["Support Group"]),  # check if keyword - already promoted
    ("ASL", ["Language Learning"]),
    ("Circus", ["Family", "Theater"]),
    ("Magic", ["Family", "Theater"]),  # check if keyword
    ("Quiet Time", ["Family"]),
    ("Diverse Voices", ["Community"]),
    ("Self Help", ["Wellness"]),
    ("Personal Growth", ["Wellness"]),  # check if keyword
    ("Starry Night", ["Science", "Outdoor"]),
    ("Night Sky", ["Science", "Outdoor"]),  # check if keyword
    ("Mannes Sounds", ["Music"]),
    ("BCC Mainstage", ["Theater"]),
    ("BCC Deep Space", ["Music"]),
    ("Galleria on Third", ["Art Gallery"]),
    ("Lobby Stage", ["Music"]),
    ("Absolute Beginner", ["Workshop"]),
]

# =============================================================================
# APPLY
# =============================================================================
added = 0
skipped_kw = []
skipped_parent = []
skipped_exists = 0

for kw_name, parent_names in mappings:
    kw_id = get_kw(kw_name)
    if not kw_id:
        skipped_kw.append(kw_name)
        continue
    for parent_name in parent_names:
        parent_id = get_curated(parent_name)
        if not parent_id:
            skipped_parent.append((kw_name, parent_name))
            continue
        if (parent_id, kw_id) in existing_edges:
            skipped_exists += 1
            continue
        cursor.execute(
            "INSERT IGNORE INTO tag_hierarchy (parent_tag_id, child_tag_id) VALUES (%s, %s)",
            (parent_id, kw_id)
        )
        if cursor.rowcount > 0:
            existing_edges.add((parent_id, kw_id))
            added += 1

print(f"Added: {added} edges")
print(f"Already existed: {skipped_exists}")
if skipped_kw:
    print(f"Keywords not found ({len(skipped_kw)}): {skipped_kw[:20]}")
if skipped_parent:
    print(f"Parents not found ({len(skipped_parent)}): {skipped_parent[:20]}")

# Cycle detection
print("\nRunning cycle detection...")
cursor.execute("SELECT parent_tag_id, child_tag_id FROM tag_hierarchy")
edges = cursor.fetchall()
from collections import defaultdict
children_of = defaultdict(set)
for e in edges:
    children_of[e['parent_tag_id']].add(e['child_tag_id'])

all_nodes = set()
for e in edges:
    all_nodes.add(e['parent_tag_id'])
    all_nodes.add(e['child_tag_id'])

WHITE, GRAY, BLACK = 0, 1, 2
color = {n: WHITE for n in all_nodes}
has_cycle = False

def dfs(node):
    global has_cycle
    color[node] = GRAY
    for child in children_of.get(node, []):
        if color[child] == GRAY:
            print(f"  CYCLE: {node} -> {child}")
            has_cycle = True
            return
        if color[child] == WHITE:
            dfs(child)
    color[node] = BLACK

for n in all_nodes:
    if color[n] == WHITE:
        dfs(n)

if has_cycle:
    print("CYCLES FOUND - rolling back!")
    conn.rollback()
else:
    print("No cycles found.")
    conn.commit()
    print("Committed successfully.")

conn.close()
